### PR TITLE
Exclude folder names from listing folder contents

### PR DESCRIPTION
**Pull request by SimonIT**

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
I understand this library as providing high-level access and that e.g. filtering for files-only, should be done by app that uses this library. 
This way the library stays very clean.

(Just my 2 cents :-))

**Comment by SimonIT** [comment]
I tried it, but it's nearly impossible. I had to copy the whole method to archive this. Filtering is only possible by checking every String via `fileExists`, which is is a quiet expensive method with over 400 files. Or am I missing something? Can you provide an example how you would do without this extension?

**Comment by tobiasKaminsky** [comment]
Ah, I am sorry! I totally read this wrong, I thought we would get something meaningful back, like File, but it is only String…
Then you are right, it seems to be the only way, right now.

**Comment by SimonIT** [comment]
I agree with you that it would be better to return something like a file object from the API, but it is how it is

**Pull request merged**
