### PR TITLE
add webdav path resolver composite

### PR DESCRIPTION
**Pull request by thestomprock**
Hi,
I added an WebDavPath resolver. This is because, my nextcloud instance ( 20.0.4) does not have the same default paths 
as the implementation on the master branch.
I added an interface where you can composite the path calculation.
The default behavior still remains the same.

Mark

### CODE REVIEW

**Comment by a-schild** [comment]
@thestomprock Thanks for your updated patch.
It indeed looks like the webdav url has changed from `server/remote.php/webdav` to `server/remote.php/dav/files/USERNAME/` somewhere arround nextcloud v12-14.

https://github.com/nextcloud/server/issues/8795

But as far as I can tell, the "old" url is still working as of nextcloud v20.0.4.
I wonder if we should implement an autodetection of the correct webdav url for the user with the given credentials...

**Comment by thestomprock** [comment]
@a-schild added auto detection of the correct path/ncVersion
Additionally to FILES I added VCARD and CALDAV  paths.
Everything defaults to the values as it was.

**Comment by tobiasKaminsky** [comment]
> But as far as I can tell, the "old" url is still working as of nextcloud v20.0.4.

Not sure how old NC server you want to support, but all suported NC version have new dav already in place, same is since NC12, so I would not go with auto detect, but simply use newest endpoint.

**Comment by a-schild** [comment]
@tobiasKaminsky Would you care to update the pull request to the latest code, so we can merge it?

**Comment by a-schild** [comment]
There is a bug in your code, in the test cases the resulting remote path is incorrect.
It constructs this:

`https://aarboard.oncloud7.ch:443/%5Cremote.php%5Cdav%5Cfiles%5Ca.schild%5Ctest6.txt/`

but correct would be:

`https://aarboard.oncloud7.ch:443/remote.php/dav/files/a.schild/test6.txt`

Some / are encoded as hex values and there are too many / at the start+end of the path

**Pull request merged**
